apiVersion: v1
kind: Service
metadata:
  name: distilleries-of-scotland-service
spec:
  selector:
    app: distilleries-of-scotland
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
