version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.21
      - image: postgres:latest  # Add a PostgreSQL service
        environment:
          POSTGRES_USER: distilleries_of_scotland_user_test
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: distilleriesdb_test

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test ./...

      - setup_remote_docker

      - run: docker version
      - run: docker build -t efuchsman/distilleries_of_scotland-distilleries_of_scotland:latest .
      - run: docker save -o /tmp/image.tar efuchsman/distilleries_of_scotland-distilleries_of_scotland:latest
      - persist_to_workspace:
          root: /tmp
          paths:
            - image.tar

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      # Install required dependencies
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y conntrack

      # Load Docker Image
      - run:
          name: Load Docker Image
          command: |
            docker load -i /tmp/image.tar

      # Install kubectl
      - run:
          name: Install kubectl
          command: |
            mkdir -p $HOME/bin
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            mv kubectl $HOME/bin/

            echo 'export PATH=$PATH:$HOME/bin' >> $HOME/.bashrc
            source $HOME/.bashrc

      # Install Minikube
      - run:
          name: Install Minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            chmod +x minikube
            sudo mv minikube /usr/local/bin/

      # Start Minikube
      - run:
          name: Start Minikube
          command: minikube start --wait=5m --vm-driver=docker --ports=8080:8080

      # Debug Docker Images
      - run:
          name: Debug Docker Images
          command: |
            docker images

      # Deploy to Minikube using kubectl
      - run:
          name: Deploy to Minikube
          command: |
            kubectl apply -f kube/pg-pvc.yaml -f kube/pg-deployment.yaml -f kube/pg-service.yaml -f kube/distilleries-of-scotland-deployment.yaml -f kube/distilleries-of-scotland-service.yaml
          when: on_success

      # Push Docker Image to Docker Hub
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push efuchsman/distilleries_of_scotland-distilleries_of_scotland:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
