environment:
  development:
    database:
      host: localhost
      port: 5432
      user: distilleries_of_scotland_user_dev
      password: dev_password
      name: distilleriesdb_dev
      connection_string: "user=distilleries_of_scotland_user_dev dbname=distilleriesdb_dev host=localhost port=5432 password=dev_password sslmode=disable"
